let mediaRecorder;
let audioChunks = [];
let recordedVoiceFile = null;

// ----------- RECORD VOICE -----------
async function startRecording() {
  audioChunks = [];

  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    mediaRecorder = new MediaRecorder(stream);

    mediaRecorder.ondataavailable = event => {
      audioChunks.push(event.data);
    };

    mediaRecorder.onstop = () => {
      const audioBlob = new Blob(audioChunks, { type: "audio/wav" });
      recordedVoiceFile = new File([audioBlob], "recorded_voice.wav", {
        type: "audio/wav"
      });

      document.getElementById("recordStatus").innerText =
        "Voice recorded successfully";
    };

    mediaRecorder.start();
    document.getElementById("recordStatus").innerText = "Recording...";
  } catch (err) {
    alert("Microphone access denied or not available.");
  }
}

function stopRecording() {
  if (mediaRecorder) {
    mediaRecorder.stop();
  }
}

// ----------- PREDICT -----------
async function predict() {
  const handwriting = document.getElementById("handwriting").files[0];
  const uploadedVoice = document.getElementById("voiceFile")?.files[0];

  if (!handwriting) {
    alert("Please upload handwriting image.");
    return;
  }

  // Priority: recorded voice > uploaded file
  const voice = recordedVoiceFile || uploadedVoice;

  if (!voice) {
    alert("Please record voice or upload a voice file.");
    return;
  }

  const formData = new FormData();
  formData.append("handwriting", handwriting);
  formData.append("voice", voice);

  document.getElementById("loader").classList.remove("hidden");
  document.getElementById("resultBox").classList.add("hidden");

  try {
    const response = await fetch("https://parkinsons-ai-backend.onrender.com/predict", {
      method: "POST",
      body: formData
    });

    if (!response.ok) {
      throw new Error("Server error");
    }

    const data = await response.json();

    const resultBox = document.getElementById("resultBox");
    const prediction = document.getElementById("prediction");
    const score = document.getElementById("score");

    resultBox.className = "";

    if (data.prediction.includes("Normal")) {
      resultBox.classList.add("normal");
    } else if (data.prediction.includes("Early")) {
      resultBox.classList.add("early");
    } else {
      resultBox.classList.add("high");
    }

    prediction.innerText = "Result: " + data.prediction;
    score.innerText = "Risk Score: " + data.final_risk_score + "%";

    // ----------- SHOW HANDWRITING HEATMAP -----------
    if (data.handwriting_explanation) {
      const heatmap = document.getElementById("heatmap");
      heatmap.src = "data:image/png;base64," + data.handwriting_explanation;
      heatmap.style.display = "block";
    }

    document.getElementById("loader").classList.add("hidden");
    resultBox.classList.remove("hidden");

  } catch (error) {
    document.getElementById("loader").classList.add("hidden");
    alert("Prediction failed. Please try again.");
    console.error(error);
  }
}

// ----------- PDF DOWNLOAD (FIXED & GUARANTEED) -----------
function downloadPDF() {
  if (!window.jspdf) {
    alert("PDF library not loaded");
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const prediction =
    document.getElementById("prediction")?.innerText || "";
  const score =
    document.getElementById("score")?.innerText || "";
  const date = new Date().toLocaleString();

  doc.setFontSize(16);
  doc.text("AI Parkinson's Screening Report", 20, 20);

  doc.setFontSize(11);
  doc.text("Date: " + date, 20, 35);

  doc.line(20, 40, 190, 40);

  doc.setFontSize(13);
  doc.text("Screening Result", 20, 55);

  doc.setFontSize(11);
  doc.text(prediction, 20, 65);
  doc.text(score, 20, 75);

  doc.line(20, 85, 190, 85);

  doc.setFontSize(10);
  doc.text(
    "This report is generated by an AI-based screening system.\n" +
    "It is intended for screening purposes only and NOT a medical diagnosis.\n" +
    "Please consult a qualified neurologist for confirmation.",
    20,
    100
  );

  doc.save("Parkinson_Screening_Report.pdf");
}


